# Generated by Django 2.1.5 on 2019-02-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
