# Generated by Django 2.1.5 on 2019-03-03 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0002_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Subject', max_length=255)),
                ('semester1', models.CharField(default='-', max_length=30)),
                ('semester2', models.CharField(default='-', max_length=30)),
                ('overall', models.CharField(default='-', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='grades',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default/default.png', upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
