# Generated by Django 2.1.5 on 2019-02-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0003_auto_20190217_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
