# Generated by Django 2.1.5 on 2019-03-05 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0003_auto_20190303_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Subject', max_length=255)),
                ('first_semester', models.CharField(default='-', max_length=30)),
                ('second_semester', models.CharField(default='-', max_length=30)),
                ('overall', models.CharField(default='-', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
