# Generated by Django 2.1.5 on 2019-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0003_auto_20190205_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
