# Generated by Django 2.1.5 on 2019-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0004_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activate',
            new_name='active',
        ),
    ]
