# Generated by Django 2.1.5 on 2019-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallsite', '0005_auto_20190206_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
